### ISSUE TITLE
Poor performance with Spectacle in IntelliJ

### ISSUE THREAD

**Issue by ocary** [getgauge/spectacle#18] opened 2018-02-26 17:12 UTC
When using IntelliJ, after installing Gauge Spectacle some edit actions of specs and IntelliJ actions are significantly slowed.  Appears to only affect .spec files.   Without Spectacle these actions run basically instantly.   

Actions that are slowed with Spectacle insalled

- Click on run icon next to the spec or scenario name to pick run, debug, etc.   (Seen to take up to 9 seconds before the context menu appears).
- Right click on filename to pick options like "close unmodified".   
- In a concept file, right click on filename to pick options like "close unmodified".   
- Click on run icon next to the spec name or scenario name
- Edit of Spec name.   (Takes 3 - 4 seconds for the typed characters to appear)
- Edit of Scenario name.

These slowdowns are seen on a project that has 6 gauge sub-projects within and overall is decently large.  2000+ specs between the 6 projects.   Less severe slowdowns are seen on a much smaller project, but the lag still is very frustrating.

### Gauge version
```
Gauge version: 0.9.7
Commit Hash: bc9784c

Plugins
-------
csharp (0.10.1)
flash (0.0.1)
html-report (4.0.3)
java (0.6.6)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)


IntelliJ Gauge plugin:   0.3.9

IntelliJ Ultimate 2017.3.4
```

**Comment by nehashri** [comment] 2018-02-27 06:48
@ocary I don't see a significant lag with spectacle installed. However, I would like to clarify a few things so I can try and see when such a lag occurs.
- Which OS are you working on?
- When do you see the lag happening? Immediately after opening the project or after running it for some time?
- When there is a lag, are there a lot of preview pages open in the browser? If so, on an average how many are open?
- Do you still see this lag after closing all the pages in the browser?

**Comment by ocary** [comment] 2018-02-27 21:53
- OS:  Windows7 Enterprise.  Service Pack 1.

- When:  Happens as soon as the project is opened.    Further details:  I uninstalled the Spectacle plugin, closed all files in IntelliJ and rebooted the machine.  I opened the project, opened 1 simple spec file (6 steps in the 1 scenario in the spec) and performance was fine.   I installed the Spectacle plugin and immediately saw the lag when trying to do any of the actions specified in the original post.  Closing the project and re-opening still has the lag present.   Uninstalling the Spectacle plugin from a command line results in the lag going away immediately in IntelliJ.

- Preview pages:  I don't know what you mean by preview pages - therefore I don't think I have any preview pages open.

**Comment by nehashri** [comment] 2018-02-28 09:31
@ocary Thanks for reporting this issue. 
Spectacle runs every time a preview call is made. This call can be made by clicking on the Browser icon in upper right corner of the editor. 
It can also be made by some plugins running in the background. One such plugin I found was [LiveEdit](https://plugins.jetbrains.com/plugin/7007-liveedit) plugin. Such plugins try to reload the preview at frequent intervals and hence may start running spectacle multiple times. 
 If you have any such plugins installed can you try disabling it and see if the same issue occurs.

**Comment by ocary** [comment] 2018-02-28 17:47
I disabled the following and am still seeing the lag:

- All custom (non-bundled with IntelliJ) plugins except Gauge.
- HTML Tools
- Less support
- QuirksMode
- Spy-js
- Thymeleaf
- W3C Validatiors


All of the above plugins that are bundled with IntelliJ were installed by default.   Looking through all the bundled plugins, these were the 6 that looked like they might have something to do with live parsing of files.

Are there any logs I should be looking into to see what is being called?

**Comment by nehashri** [comment] 2018-03-01 08:16
@ocary I have pushed a commit onto gauge intellij plugin. Could you take the latest nightly of Gauge Intellij plugin and test it. Unfortunately, I am not able to reproduce the exact same issue you are facing. I have added a commit which shows the preview only if required. Could you please try this out and let us know if it fixes your issue.

PS: Refer [here](https://docs.gauge.org/using.html#installing-nightly) to subscribe to the nightly channel of Intellij Gauge plugin. The plugin with the fix should be available in nightly version >= 0.3.9.nightly-2018-03-01.

**Comment by ocary** [comment] 2018-03-01 21:10
Installed IntelliJ-Gauge plugin 0.3.9.nightly-2018-03-01 and Spectacle 0.1.2.   No lag seen in the operations listed in the original post.   Also, when Spectacle is not installed, the IntelliJ event log no longer fills with "Missing plugin... spectacle" messages.   Missing plugin only shows when you click on a browser preview icon.

Looks good.  Thank you.

**Comment by nehashri** [comment] 2018-03-02 04:29
@ocary Good to hear this :)

**Closed** 2018-03-06 04:01 UTC
Labels: ready for QA

**Comment by nehashri** [comment] 2018-03-06 07:03
@ocary We have released a [new version of Gauge Intellij Plugin](https://plugins.jetbrains.com/plugin/7535-gauge/update/43881). So the fix should be available with the latest released version.
